from_latest_tag = false
tag_prefix = "v"
ignore_merge_commits = false
ignore_fixup_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = false
generate_mono_repository_package_tags = false
branch_whitelist = []
pre = "alpha.*"
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "echo 'bumping from {{latest|0.0.0}} to {{version|0.0.1}}'",
  "perl -pi -e 's/^(project\\(safety_mesh VERSION )[0-9]+\\.[0-9]+\\.[0-9]+/${1}{{version}}/' CMakeLists.txt",
  "cmake -S . -B build",
  "cmake --build build",
  "git add CMakeLists.txt",
]
post_bump_hooks = ["git push", "git push origin v{{version}}"]

pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[git_hooks.commit-msg]
script = '''#!/bin/sh
set -e
cog verify --file "$1"
'''

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]
