#pragma once

#define SAFETY_MESH_VERSION_MAJOR 0
#define SAFETY_MESH_VERSION_MINOR 0
#define SAFETY_MESH_VERSION_PATCH 1

#define SAFETY_MESH_STRINGIFY_IMPL(value) #value
#define SAFETY_MESH_STRINGIFY(value) SAFETY_MESH_STRINGIFY_IMPL(value)
#define SAFETY_MESH_VERSION \
    SAFETY_MESH_STRINGIFY(SAFETY_MESH_VERSION_MAJOR) "." \
    SAFETY_MESH_STRINGIFY(SAFETY_MESH_VERSION_MINOR) "." \
    SAFETY_MESH_STRINGIFY(SAFETY_MESH_VERSION_PATCH)

namespace safety_mesh {

inline constexpr const char* version = SAFETY_MESH_VERSION;

}
